--UPPER KOMUTU BUYUK HARF
--LOWER KOMUTU KUCUK HARF
--SELECT UPPER ('merhaba') as 'SÜTUN'
--SELECT UPPER(OGRAD) AS 'ÝSÝM', UPPER(OGRSOYAD) AS 'SOYAD' ,
--LOWER(OGRSEHÝR) AS 'SEHÝR'
--FROM Tbl_Ogrenciler
--ODEV-1
--Select Upper(OGRAD) +' '+ Lower(OGRSOYAD) As 'Öðrenci AdSoyad' From Tbl_Ogrenciler
--where OGRSEHÝR='Adana' and OGRKULUP=(Select KULUPID From Tbl_Kulupler where KULUPAD='Kitaplýk')



--SUBSTRÝNG KOMUTU
--SELECT SUBSTRING(OGRAD,1,1) + '.' + OGRSOYAD  FROM Tbl_Ogrenciler
--ODEV-2
--Select Substring(OGRAD,1,1) +'.'+ OGRSOYAD As 'AD SOYAD', Substring(KULUPAD,1,3) As 'KULUP' From Tbl_Ogrenciler
--Inner Join Tbl_Kulupler On Tbl_Ogrenciler.OGRKULUP=Tbl_Kulupler.KULUPID



--LEFT RIGHT KOMUTLARI
--SELECT LEFT('MERHABA DÜNYA',4)
--SELECT RIGHT('MERHABA DÜNYA',4)
--SELECT LEFT(OGRAD,1) + '.'+OGRSOYAD FROM Tbl_Ogrenciler



--LEN KOMUTU
--SELECT LEN('MERHABA')
--SELECT OGRAD,LEN(OGRAD),OGRKULUP FROM Tbl_Ogrenciler WHERE OGRSEHÝR='Erzurum' and
--OGRKULUP=(select kulupýd from Tbl_Kulupler where KULUPAD='Kitaplýk')
--select * from Tbl_Ogrenciler where len(ograd)=4 or len(ograd)=3
 --ODEV-3
-- SELECT OGRAD,OGRSOYAD FROM Tbl_Ogrenciler
--WHERE LEN(OGRAD)+LEN(OGRSOYAD) BETWEEN 3 AND 7


--LTRÝM RTRÝM REPLACE
--SELECT LTRIM('          KORKMA SONMEZ BU ÞAFAKLARDA YÜZEN AL SANCAK')
--SELECT RTRIM(' KORKMA SONMEZ BU ÞAFAKLARDA YÜZEN AL SANCAK      ')
--SELECT REPLACE('YASÝN BULUT','YASÝN','M.YAS')
--1.PARAMETRE=ANA KELÝME CÜMLE
--2.PARAMETRE=DEÐÝÞECEK DEÐER
--3.PARAMETRE=YENÝ DEÐER


--CHARINDEX REVERSE KOMUTLAARI
--SELECT CHARINDEX('E','SQL DERSLERÝNE DEVAM EDÝYORUZ',15)
--SELECT LEN('SQL DERSLERÝNE DEVAM EDÝYORUZ')
--SELECT REVERSE('YASÝN')
--SELECT REVERSE(DERSAD) FROM Tbl_Dersler
 