--SELECT URUNAD ,COUNT(*) FROM Tbl_Hareket
--INNER JOIN Tbl_Urunler ON Tbl_Hareket.URUN=Tbl_Urunler.URUNID
--GROUP BY URUNAD ORDER BY COUNT(*) ASC

--SELECT * FROM Tbl_Hareket WHERE URUN IN (SELECT URUNID FROM Tbl_Urunler WHERE 
--KATEGORI=1)

--ODEV
--Select * From Tbl_Hareket Where URUN in(Select URUNID From Tbl_Urunler Where KATEGORI=(Select KATEGORIID From Tbl_Kategori WHERE KATEGORIAD='BÝLGÝSAYAR'))

--ADANALILARA AÝT HARCAMALAR
--SELECT * FROM Tbl_Hareket WHERE MUSTERI IN(SELECT MUSTERIID FROM Tbl_Musteri
--WHERE MUSTERISEHIR='ADANA')

--SELECT * FROM Tbl_Hareket WHERE URUN IN(SELECT URUNID FROM Tbl_Urunler WHERE 
--KATEGORI=(SELECT KATEGORIID FROM Tbl_Kategori WHERE KATEGORIAD='BEYAZ EÞYA'))

--SELECT SUM(TUTAR) FROM Tbl_Hareket WHERE MUSTERI IN(SELECT MUSTERIID FROM Tbl_Musteri
--WHERE MUSTERISEHIR='ADANA' or MUSTERISEHIR='ANKARA')

--select * from Tbl_Hareket where urun=1
--UPDATE Tbl_Urunler SET URUNSTOK= URUNSTOK-(SELECT SUM(ADET) FROM Tbl_Hareket WHERE
--URUN=1) WHERE URUNID=1

--CREATE TABLE KASA
--(
--TOPLAM DECIMAL(18,2)
--)

--INSERT INTO Tbl_Kasa VALUES (0)
--SELECT * FROM TBL_Kasa

--UPDATE TBL_KASA SET TOPLAM=	(SELECT SUM(TUTAR) FROM Tbl_Hareket)