--SELECT  20+4 AS 'TOPLAM' ,20-4 AS 'FARK',20*4 AS 'ÇARPIM',20/4 AS 'BOLUM'

--SELECT * FROM Tbl_Notlar WHERE DERS=1
--UPDATE Tbl_Notlar SET SINAV2=SINAV2+10 FROM Tbl_Notlar WHERE DERS=1
--UPDATE Tbl_Notlar SET SINAV2=100 WHERE SINAV2>100
--SELECT * FROM Tbl_Notlar WHERE DERS=1
--select avg(ortalama) from Tbl_Notlar where ders=1

--select * from Tbl_Notlar 

--ABS MUTLAK DEÐER 
--SELECT ABS(-85) AS 'MUTLAK'

--POWER US ALMA
--SELECT POWER(4,2) AS 'US '
--SELECT POWER(SINAV1,2) FROM Tbl_Notlar

--SQRT KOMUTU KARAKOK
--SELECT SQRT(625)

--FLOOR TABANA YUVARLAMA
--SELECT FLOOR(4.86)

--CEELÝNG KOMUTU TAVANA YUVARLAMA
--SELECT CEILING(4.86)

--SUM KOMUT TOPLAMA
--SELECT SUM(SINAV1) FROM Tbl_Notlar WHERE OGRENCÝ=1
--SELECT SINAV1,DERS FROM Tbl_Notlar WHERE OGRENCÝ=1
--SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM Tbl_Notlar INNER JOIN Tbl_Dersler ON Tbl_Notlar.DERS=Tbl_Dersler.DERSID
--WHERE OGRENCÝ=(SELECT OGRID FROM Tbl_Ogrenciler WHERE OGRAD='Yasin' and OGRSOYAD='Bulut')

--AVG ORTALAMA DEÐER
SELECT SUM(SINAV1),AVG(SINAV1) FROM Tbl_Notlar INNER JOIN Tbl_Dersler
 ON Tbl_Notlar.DERS=Tbl_Dersler.DERSID
WHERE OGRENCÝ=(SELECT OGRID FROM Tbl_Ogrenciler WHERE OGRAD='Yasin' and OGRSOYAD='Bulut')


