--SELECT * FROM Tbl_Hareket where DATEPART(DAY,TARIH) BETWEEN 3 AND 5

--SELECT * FROM Tbl_Hareket WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND 
--MUSTERI=(SELECT MUSTERIID FROM Tbl_Musteri WHERE MUSTERISEHIR='ANKARA'),


--SELECT DATENAME(MONTH,GETDATE()),DATENAME(MONTH,'2019.01.15')

--SELECT DATENAME(DAY,GETDATE())
--SELECT DATENAME(WEEKDAY,GETDATE())
--SELECT DATENAME(WEEKDAY,'2019.06.10')


--SELECT DATEDIFF(YEAR,'2010.10.25',GETDATE())
--SELECT DATEDIFF(MONTH,'2010.06.14',GETDATE())
 --SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM Tbl_Hareket WHERE HAREKETID=1


 --SELECT DATEADD(YEAR,3,'2009-10-25')
 --SELECT DATEADD(DAY,10,GETDATE())
 --SELECT DATEADD(MONTH,3,GETDATE())