--insert into Tbl_Kategori (KATEGORIAD) VALUES ('BÝLGÝSAYAR')
--insert into Tbl_Kategori (KATEGORIAD) VALUES ('BEYAZ EÞYA')
--insert into Tbl_Kategori (KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')
--insert into Tbl_Kategori (KATEGORIAD) VALUES ('TV')

--insert into Tbl_Urunler (URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATIS,URUNSTOK) 
--VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)

--	select * from Tbl_Urunler

--UPDATE Tbl_Urunler set URUNAD='KETTLE' WHERE URUNAD='SU ISSITICI'

--SELECT	 KATEGORIAD,COUNT (*) FROM Tbl_Urunler INNER JOIN Tbl_Kategori 
--ON Tbl_Urunler.KATEGORI=Tbl_Kategori.KATEGORIID GROUP BY KATEGORIAD ORDER BY COUNT(*)

--KATEGORI ADI BÝLGÝSAYAR OLAN URUNLERE 500TL ZAM
--UPDATE Tbl_Urunler set URUNSATIS+=500 WHERE KATEGORI=(SELECT KATEGORIID FROM Tbl_Kategori WHERE KATEGORIAD='BÝLGÝSAYAR')

--SELECT COUNT(*)  AS 'KAÇ FARKLI URUN',SUM(URUNSTOK) FROM Tbl_Urunler

--SELECT * FROM Tbl_Urunler

--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATIS,URUNALISFIYAT,URUNSTOK,
--(URUNSATIS-URUNALISFIYAT) as 'kar',(URUNSATIS-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR'
-- FROM Tbl_Urunler INNER JOIN Tbl_Kategori
--ON Tbl_Urunler.KATEGORI =Tbl_Kategori.KATEGORIID