--USE DBYENÝ
--SELECT * FROM TBL_URUN

--FONKSÝYON OLUÞTURMA
--CREATE FUNCTION STOKARTTIR(@ADET INT)
--RETURNS INT 
--AS
--BEGIN
--RETURN @ADET+26
--END

--SELECT AD,STOK,DBO.STOKARTTIR(STOK) AS 'ARTTIRILMIÞ HALÝ' FROM TBL_URUN


--ODEV
--CREATE FUNCTION ODEVFUNCTION (@DEGER DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN SQRT(@DEGER)*3
--END
--SELECT AD,STOK,DBO.ODEVFUNCTION(STOK) FROM TBL_URUN


--ALTER FUNCTION KUCUKHARF (@ISIM VARCHAR(20))
--RETURNS VARCHAR(20)
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END
--SELECT DBO.KUCUKHARF(AD),STOK FROM TBL_URUN

--CREATE FUNCTION KDV(@FIYAT DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN @FIYAT*1.18
--END
--select AD,SATISFIYAT,DBO. KDV(SATISFIYAT) FROM TBL_URUN

--CREATE FUNCTION URUNBILGI(@URID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBL_URUN WHERE URUNID=@URID
--SELECT * FROM DBO.URUNBILGI(4)
