--PRESEDUR

--CREATE PROCEDURE HAREKETLER
--AS 

--SELECT HAREKETID,URUNAD,MUSTERIAD + '' + MUSTERÝSOYAD as 'AD SOYAD',
--PERSONELADSOYAD,ADET,TUTAR,TARIH
--FROM Tbl_Hareket  INNER JOIN Tbl_Urunler
--ON Tbl_Hareket.URUN=Tbl_Urunler.URUNID
--INNER JOIN Tbl_Musteri
--on Tbl_Hareket.MUSTERI=Tbl_Musteri.MUSTERIID
--INNER JOIN Tbl_Personel
--ON Tbl_Hareket.PERSONEL=Tbl_Personel.PERSONELID 



--PROSODUR SÝLME
	--DROP PROCEDURE ÝSÝM

--ALTER  PROCEDURE URUNGETIR
--@DEGER VARCHAR(50)='BUZDOLABI'
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM Tbl_Urunler
--WHERE URUNAD=@DEGER

--EXECUTE URUNGETIR @DEGER='LAPTOP'

