--declare @sayi int
--set @sayi=25
--select @sayi

--declare @kisi1 varchar(20) 
--set @kisi1='ALÝ'
--select @kisi1  as 'ÝSÝM'

--DECLARE @SAYI1 INT,@SAYI2 INT, @TOPLAM INT 
--SET @SAYI1=20
--SET @SAYI2=30
--SET @TOPLAM=@SAYI1+@SAYI2
--SELECT @TOPLAM  AS 'TOPLAM'

--declare @sinav1 float ,@sinav2 float ,@sinav3 float ,@ortalama float
--set @sinav1=56
--set @sinav2=78
--set @sinav3=29
--set @ortalama=(@sinav1+@sinav2+@sinav3)/3
--select @ortalama as ortalama

--123 = 6
--DECLARE @SAYÝ INT,@BIRLER INT,@ONLAR INT,@YUZLER INT,@TOPLAM INT 
--SET @SAYÝ=456
--SET @BIRLER= @SAYÝ %10
--SET @ONLAR= (@SAYÝ / 10)%10
--SET @YUZLER= @SAYÝ / 100
--SET @TOPLAM=@BIRLER+@ONLAR+@YUZLER
--SELECT @TOPLAM AS 'TOPLAM DEGER'

--USE SatisVT
--SELECT * FROM Tbl_Musteri
--DECLARE @BAKIYE INT 
--SET @BAKIYE=(SELECT MAX(MUSTERIBAKIYE) FROM Tbl_Musteri)
--SELECT @BAKIYE

--SELECT * FROM Tbl_Urunler
--DECLARE @STOK INT
--SELECT @STOK=MAX(URUNSTOK) FROM Tbl_Urunler
--SELECT @STOK
--SELECT * FROM Tbl_Urunler WHERE URUNSTOK=@STOK

--SELECT @@SERVERNAME,@@ERROR,@@DEFAULT_LANGID,@@LANGUAGE,@@MAX_CONNECTIONS,
--@@MICROSOFTVERSION,@@IDENTITY,@@TEXTSIZE,@@VERSION

--PRINT 'MERHABA'

--DECLARE @S1 INT,@S2 INT, @SONUC INT
--SET @S1=4
--SET @S2=8
--SET @SONUC = @S1*@S2
--PRINT '4 ÝLE 8 SAYILARININ ÇARPIMI'
--PRINT '**************************'
--PRINT @SONUC

--DECLARE @KISILER TABLE
--(
--KISIID INT IDENTITY(1,1),
--KISIAD VARCHAR(10),
--KISISEHIR VARCHAR(15)
--)
--INSERT INTO @KISILER (KISIAD,KISISEHIR) VALUES ('ALÝ','MALATYA')
-- INSERT INTO @KISILER  (KISIAD,KISISEHIR) VALUES ('YASÝN','ÝSTANBUL')
--SELECT * FROM @KISILER

--IF(1<5)
--PRINT 'MERHABA'
--ELSE
--PRINT 'SELAM' 

--SELECT * FROM Tbl_Urunler
--IF(SELECT SUM(URUNSTOK) FROM Tbl_Urunler)>100
--PRINT 'TOPLAM URUN SAYISI 100 DEN BUYUK'
--ELSE
--PRINT 'TOPLAM URUN SAYISI 100 DEN KUCUK'

--ODEV
--declare @stok int
--set @stok=(select SUM(UrunStok) from Tbl_Urunler)
--if @stok> 100
--print 'Toplam Urun Sayisi:'+ cast (@stok as varchar)

--SELECT URUNAD,URUNMARKA,URUNDURUM=
--CASE URUNDURUM 
--WHEN '1' THEN 'URUN VAR'
--WHEN '0' THEN 'URUN YOK'
--END
--FROM Tbl_Urunler

--SELECT URUNAD,URUNMARKA,KATEGORI=
--CASE KATEGORI 
--WHEN '1' THEN 'LAPTAP'
--WHEN '2' THEN 'BEYAZ EÞYA'
--WHEN '3' THEN 'KÜÇÜK EV EÞYASI'
--WHEN '4' THEN 'TV'
--END
--SELECT * FROM  Tbl_Urunler

--CREATE PROCEDURE TEST4
--AS
--SELECT URUNAD,URUNMARKA,URUNSTOK,URUNSTOK=
--CASE 
--WHEN URUNSTOK>=1 AND URUNSTOK<=5 THEN 'KRÝTÝK SEVÝYE'
--when URUNSTOK>=6 AND URUNSTOK<=10 THEN 'TAKVÝYE YAPILMALI'
--WHEN URUNSTOK>10 THEN 'ÜRÜN STOK SAYISI YETERLÝ'
--END
--FROM Tbl_Urunler

--WHÝLE KULLANIM
--declare @sayac int
--set @sayac=1
--while @sayac<=5
--begin
--print 'MERHABA SQL DERSLERÝ'
--set @sayac=@sayac +1
--end	

--DECLARE @I INT
--SET @I=1
--WHILE @I<10
--BEGIN 
--SET @I+=1
--PRINT @I
--END

--DECLARE @TOPLAM INT ,@SAYAC INT
--SET @SAYAC=1
--SET @TOPLAM=0
--WHILE (@SAYAC<=10)
--BEGIN 
--SET @TOPLAM=@TOPLAM+@SAYAC
--SET @SAYAC+=1
--END
--PRINT '1 ÝLE 10 ARASINDAKÝ SAYILARIN TOPLAMI'
--PRINT @TOPLAM	

--SELECT AVG(URUNSATIS-URUNALISFIYAT) FROM Tbl_Urunler WHERE KATEGORI=2

--UPDATE Tbl_Urunler SET URUNSATIS+=URUNSATIS*10/100

--WAITFOR DELAY '00:00:07'
--SELECT * FROM Tbl_Urunler

--WAITFOR DELAY '00:00:05'
--INSERT INTO Tbl_Kategori (KATEGORIAD) VALUES ('DÝÐER')
--SELECT * FROM Tbl_Kategori