--USE DBYENÝ

--TRANSACTION -->ROLLBACK COMMIT
--BANKAMATÝKTEN PARAYI ÇEKMEYÝP GERÝ PARA GÝDÝNCE
--UPDATE TBLHESAP SET BAKIYE=250 WHERE=12345
--800 -->550
--800 -->550+250 -->800

--BEGIN TRANSACTION 
--INSERT INTO TBL_KATEGORI (AD) VALUES ('TV')
--INSERT INTO TBL_KATEGORI (AD) VALUES ('HALI')
--SELECT * FROM TBL_KATEGORI
--ROLLBACK -- ÝÞLEMLERÝ GERÝ ALIR


BEGIN TRANSACTION
INSERT INTO TBL_URUN (AD,STOK) VALUES ('URUN3',10)
INSERT INTO TBL_URUN (AD,STOK) VALUES ('URUN4','B')
SELECT * FROM TBL_URUN
COMMIT	-- HATALI ÝÞLEM OLURSA ÝKÝSÝNÝDE ÝPTAL EDER YA HEP YA HÝÇ