--CREATE DATABASE DBYENÝ	
--USE DBYENÝ
--CREATE TABLE TBL_MUSTERI
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--SOYAD VARCHAR(20),
--SEHIR VARCHAR(15),
--BAKIYE DECIMAL(18,2)
--)

--CREATE TABLE TBL_KATEGORI
--(
--KATEGORIID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--)

--CREATE TABLE TBL_URUN
--(
--URUNID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--ALISFIYAT DECIMAL(18,2),
--SATISFIYAT DECIMAL(18,2),
--STOK SMALLINT,
--DURUM BIT,
--KATEGORI INT
--)

--CREATE TABLE TBL_SATIS
--(
--URUNID INT PRIMARY KEY IDENTITY(1,1),
--MUSTERI INT,
--URUN INT,
--TARIH DATE
--)

--use DBYENÝ
--UPDATE TBL_STOK SET TOPLAMURUN=(
--SELECT COUNT(*) FROM TBL_URUN)

--create TRIGGER ARTTIR
--ON TBL_URUN
--AFTER INSERT 
--AS
--UPDATE TBL_STOK SET TOPLAMURUN+=1

--UPDATE TBL_STOK SET TOPLAMURUN=(SELECT SUM(STOK) FROM TBL_URUN) 

--SÝLME
--DROP TRIGGER ARTTIR

--CREATE TRIGGER ARTTIR
--ON TBL_URUN
--AFTER INSERT
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI=STOK FROM INSERTED
--UPDATE TBL_STOK SET TOPLAMURUN+=@STOKSAYI

--CREATE TRIGGER AZALT
--ON TBL_URUN
--AFTER DELETE 
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI=STOK FROM DELETED
--UPDATE TBL_STOK SET TOPLAMURUN=TOPLAMURUN-@STOKSAYI

--INSERT INTO TBL_URUN (AD,STOK) VALUES ('MÝKER',80)