--CREATE VIEW TEST1
--AS
--SELECT * FROM Tbl_Kategori
--select * from TEST1
--ALTER VIEW TEST1
--AS
--SELECT * FROM Tbl_Kategori WHERE KATEGORIID<4

--SELECT * FROM TEST1


--SELECT * FROM TEST2

SELECT * FROM TEST3
